name: custom_chatgpt_chatbot
channels:
  - defaults
dependencies:
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - openssl=1.1.1t
  - pip=22.3.1
  - python=3.8.13
  - setuptools=65.6.3
  - sqlite=3.40.1
  - wheel=0.38.4
  - pip:
    - astroid==2.15.0
    - attrs==22.2.0
    - autocorrect==2.6.1
    - beautifulsoup4==4.11.2
    - black==23.1.0
    - blobfile==2.0.1
    - bs4==0.0.1
    - charset-normalizer==2.1.1
    - colorama==0.4.6
    - contourpy==1.0.7
    - cycler==0.11.0
    - dill==0.3.6
    - filelock==3.9.0
    - flask==2.2.3
    - fonttools==4.39.0
    - huggingface-hub==0.12.1
    - idna==3.4
    - importlib-metadata==6.0.0
    - isort==5.12.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - joblib==1.2.0
    - kiwisolver==1.4.4
    - langdetect==1.0.9
    - lazy-object-proxy==1.9.0
    - lxml==4.9.2
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mccabe==0.7.0
    - mypy-extensions==1.0.0
    - nltk==3.8.1
    - numpy==1.23.5
    - openai==0.27.0
    - packaging==23.0
    - pandas==1.5.3
    - pathspec==0.11.0
    - pillow==9.4.0
    - platformdirs==3.1.0
    - pycryptodomex==3.17
    - pylint==2.16.4
    - pyparsing==3.0.9
    - python-dateutil==2.8.2
    - pytz==2022.7.1
    - pyyaml==6.0
    - regex==2022.10.31
    - requests==2.28.2
    - scipy==1.10.1
    - six==1.16.0
    - soupsieve==2.4
    - tenacity==8.2.2
    - threadpoolctl==3.1.0
    - tiktoken==0.3.0
    - tokenizers==0.13.2
    - tomli==2.0.1
    - tomlkit==0.11.6
    - tqdm==4.65.0
    - transformers==4.26.1
    - typing-extensions==4.5.0
    - urllib3==1.26.14
    - werkzeug==2.2.3
    - wrapt==1.15.0
    - zipp==3.15.0
